### ISSUE TITLE
There is no configuration to close the circled part in the figure below

### ISSUE THREAD

**Issue by moatkon** [trueberryless/starlight-view-modes#6]
![image](https://github.com/trueberryless/starlight-view-modes/assets/150421704/919fa0f5-8555-42d2-8550-00dd01cd3a41)

**Comment by trueberryless** [comment]
Thank you very much for your feature request!

An option should be available in version 0.6.0! If you want to try it out and comment if it works as you'd liked, feel welcomed!
I'll close the PR for now...

**Comment by trueberryless** [comment]
You can find the option here: https://starlight-view-modes.trueberryless.org/configuration/#zenmodeshowswitchintableofcontents

**Comment by moatkon** [comment]
0.6.0 worked,thank you
